//first project with dart
 var x=8;
void main() {
 var y =0.1223;;
 print(x);
 print(y);
 String name= "Sara";
 String name1= 'Ali';
 print(name);
 print(name1);
 dynamic message = 'Hello';
 message = 8;
 print(message);
 var name2 ="Sarsooooooooor";
 print(name2);
 var car ;
 car=2;
 car='Hello';
 print(car);
 final String n="Welcome to my project";
 print(n);
const String m="Welcome to my project";
 print(n);
 List myList =[1,2,3,4,5,6,7,8,9,10];
myList.add(11);
myList.insert(0, 0);
 myList.insert(0, 'Sara');
 print(myList);
 print(myList.length);
 print(myList.first);
 print(myList.last);
 print(myList.isEmpty);
 print(myList.isNotEmpty);
 print(myList.reversed);
 print(myList[1]);
 myList.add(12);
 print(myList);
 myList[2]=20;
 print(myList);
 List sara=['ali' ,'mohammed','alaa','mona','tamer','tarek','alaa'];
 print(sara);
 Set <String> sara1= {'ali', 'mohammed', 'alaa', 'mona', 'tamer', 'tarek', 'alaa'};
 print(sara1);
Set mySet={'sara','mona','menna'};
myList.addAll(mySet);
 print(myList);
Map  myMap={'User Name ':'Sara', 'Password' :'123456'};
 myMap['User Name'] ='Sarsoooooooooooor';
 myMap['Password'] = '1222222345678';
 print(myMap);
}